/** `com.humano.domain.enumeration.hr.ApprovalType`. */
export enum ApprovalType {
  LEAVE_REQUEST = 'LEAVE_REQUEST',
  EXPENSE_CLAIM = 'EXPENSE_CLAIM',
  OVERTIME_REQUEST = 'OVERTIME_REQUEST',
  TRAINING_REQUEST = 'TRAINING_REQUEST',
  POSITION_TRANSFER = 'POSITION_TRANSFER',
  SALARY_ADJUSTMENT = 'SALARY_ADJUSTMENT',
  TIMESHEET_APPROVAL = 'TIMESHEET_APPROVAL',
}
