/** `com.humano.domain.enumeration.TenantStatus`. */
export enum TenantStatus {
  PENDING_SETUP = 'PENDING_SETUP',
  PROVISIONING = 'PROVISIONING',
  PROVISIONING_FAILED = 'PROVISIONING_FAILED',
  ACTIVE = 'ACTIVE',
  SUSPENDED = 'SUSPENDED',
  MIGRATION_FAILED = 'MIGRATION_FAILED',
  DEACTIVATED = 'DEACTIVATED',
  DELETED = 'DELETED',
}
